// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// This file will be automatically regenerated when your Next.js server is running.
/* eslint-disable */

// prettier-ignore
declare module "nextjs-routes" {
  export type Route =
    | StaticRoute<"/Data/Home/Features">
    | StaticRoute<"/Data/Home/PageLinks">
    | StaticRoute<"/Data/Home/Services">
    | StaticRoute<"/Layout/HocFront">
    | StaticRoute<"/api/hello">
    | DynamicRoute<"/api/trpc/[trpc]", { "trpc": string }>
    | StaticRoute<"/cloud-hosting/Components/FaqBlock">
    | StaticRoute<"/cloud-hosting/Components/Features">
    | StaticRoute<"/cloud-hosting/Components/OsApp">
    | StaticRoute<"/cloud-hosting/Components/PricingConfig">
    | StaticRoute<"/cloud-hosting/Components/Section1">
    | StaticRoute<"/cloud-hosting/Components/Section1Block">
    | StaticRoute<"/cloud-hosting/Components/Section2">
    | StaticRoute<"/cloud-hosting/Components/Section3">
    | StaticRoute<"/cloud-hosting/Widgets/OsList">
    | StaticRoute<"/cloud-hosting/Widgets/PricingTable">
    | StaticRoute<"/cloud-hosting">
    | StaticRoute<"/components/CloudHosting/HeroBlock">
    | StaticRoute<"/components/Footer">
    | StaticRoute<"/components/Header">
    | StaticRoute<"/components/Home/ClientSection">
    | StaticRoute<"/components/Home/HomeHero">
    | StaticRoute<"/components/Home/SectionD">
    | StaticRoute<"/components/Home/SectionFive">
    | StaticRoute<"/components/Home/SectionFour">
    | StaticRoute<"/components/Home/SectionNine">
    | StaticRoute<"/components/Home/SectionOne">
    | StaticRoute<"/components/Home/SectionSeven">
    | StaticRoute<"/components/Home/SectionSix">
    | StaticRoute<"/components/Home/SectionThree">
    | StaticRoute<"/components/Home/SectionTwo">
    | StaticRoute<"/components/Home/SectionWordpress">
    | StaticRoute<"/components/Home/WordmapComponent">
    | StaticRoute<"/components/Icons/AngularJSIcon">
    | StaticRoute<"/components/Icons/AntMediaServerIcon">
    | StaticRoute<"/components/Icons/ApiIcon">
    | StaticRoute<"/components/Icons/AutorenewalIcon">
    | StaticRoute<"/components/Icons/BackupIcon">
    | StaticRoute<"/components/Icons/BackupIcon2">
    | StaticRoute<"/components/Icons/BackupIcon3">
    | StaticRoute<"/components/Icons/BandwidthIcon">
    | StaticRoute<"/components/Icons/CentOSIcon">
    | StaticRoute<"/components/Icons/CertificateIcon">
    | StaticRoute<"/components/Icons/CertifiedIcon">
    | StaticRoute<"/components/Icons/CloudHostingIcon">
    | StaticRoute<"/components/Icons/CloudLinuxIcon">
    | StaticRoute<"/components/Icons/CloudServerWIcon">
    | StaticRoute<"/components/Icons/CloudronIcon">
    | StaticRoute<"/components/Icons/CmsIcon">
    | StaticRoute<"/components/Icons/CpanelIcon">
    | StaticRoute<"/components/Icons/CpanelIcon2">
    | StaticRoute<"/components/Icons/Cyberpanelicon">
    | StaticRoute<"/components/Icons/DataProcessingIcon">
    | StaticRoute<"/components/Icons/DataTransferIcon">
    | StaticRoute<"/components/Icons/DatabaseIcon2">
    | StaticRoute<"/components/Icons/DdosIcon">
    | StaticRoute<"/components/Icons/DdosIcon2">
    | StaticRoute<"/components/Icons/DebianIcon">
    | StaticRoute<"/components/Icons/DedicateServer1Icon">
    | StaticRoute<"/components/Icons/DedicatedServerIcon">
    | StaticRoute<"/components/Icons/DnsManagementIcon">
    | StaticRoute<"/components/Icons/DomainLockIcon">
    | StaticRoute<"/components/Icons/DomainNameIcon">
    | StaticRoute<"/components/Icons/FedoraIcon">
    | StaticRoute<"/components/Icons/FirewallIcon">
    | StaticRoute<"/components/Icons/ForwardIcon">
    | StaticRoute<"/components/Icons/FreeDomainIcon">
    | StaticRoute<"/components/Icons/GatsbyJsIcon">
    | StaticRoute<"/components/Icons/GitlabIcon">
    | StaticRoute<"/components/Icons/GrafanaIcon">
    | StaticRoute<"/components/Icons/HostingIcon">
    | StaticRoute<"/components/Icons/HostingIconHW">
    | StaticRoute<"/components/Icons/HostspacingIcon">
    | StaticRoute<"/components/Icons/InstallerIcon">
    | StaticRoute<"/components/Icons/InstallerIcon2">
    | StaticRoute<"/components/Icons/JenkinsIcon">
    | StaticRoute<"/components/Icons/JoomlaIcon">
    | StaticRoute<"/components/Icons/KeplerbuilderIcon">
    | StaticRoute<"/components/Icons/LaravelIcon">
    | StaticRoute<"/components/Icons/LayoutIcon">
    | StaticRoute<"/components/Icons/LifebuoyIcon">
    | StaticRoute<"/components/Icons/MagentoIcon">
    | StaticRoute<"/components/Icons/ManagedServerIcon">
    | StaticRoute<"/components/Icons/ManagementIcon">
    | StaticRoute<"/components/Icons/MoneyBackIcon">
    | StaticRoute<"/components/Icons/NextjsIcon">
    | StaticRoute<"/components/Icons/NodejsIcon">
    | StaticRoute<"/components/Icons/NuxtJsIcon">
    | StaticRoute<"/components/Icons/OpenSuseIcon">
    | StaticRoute<"/components/Icons/OpenVpnIcon">
    | StaticRoute<"/components/Icons/OwncastIcon">
    | StaticRoute<"/components/Icons/PerformanceIcon">
    | StaticRoute<"/components/Icons/PleskIcon">
    | StaticRoute<"/components/Icons/PleskIcon2">
    | StaticRoute<"/components/Icons/PrivacyIcon">
    | StaticRoute<"/components/Icons/RatingIcon">
    | StaticRoute<"/components/Icons/RedisIcon">
    | StaticRoute<"/components/Icons/RocketIcon">
    | StaticRoute<"/components/Icons/SSDDriveIcon">
    | StaticRoute<"/components/Icons/SSLFeature">
    | StaticRoute<"/components/Icons/SecurityIcon">
    | StaticRoute<"/components/Icons/ServerControlIcon">
    | StaticRoute<"/components/Icons/SettingsIcon2">
    | StaticRoute<"/components/Icons/ShareHostingWIcon">
    | StaticRoute<"/components/Icons/SharedHostingIcon">
    | StaticRoute<"/components/Icons/ShieldPrivacyIcon">
    | StaticRoute<"/components/Icons/SpeedTestIcon">
    | StaticRoute<"/components/Icons/SsdSardIcon">
    | StaticRoute<"/components/Icons/StudentsIcon">
    | StaticRoute<"/components/Icons/SupportIcon">
    | StaticRoute<"/components/Icons/SupportIcon2">
    | StaticRoute<"/components/Icons/SupportIcon3">
    | StaticRoute<"/components/Icons/Time60Icon">
    | StaticRoute<"/components/Icons/TimeSecondIcon">
    | StaticRoute<"/components/Icons/UbuntuIcon">
    | StaticRoute<"/components/Icons/VerifyIcon">
    | StaticRoute<"/components/Icons/VmServerIconWhite">
    | StaticRoute<"/components/Icons/VolumeIcon">
    | StaticRoute<"/components/Icons/VpsIcon">
    | StaticRoute<"/components/Icons/VpsIcon1">
    | StaticRoute<"/components/Icons/VpsServerIcon">
    | StaticRoute<"/components/Icons/WebsiteBuilderIcon">
    | StaticRoute<"/components/Icons/WindowsIcon">
    | StaticRoute<"/components/Icons/WordpressIcon">
    | StaticRoute<"/components/Icons/WordpressIconW">
    | StaticRoute<"/components/Icons/WpHIcon">
    | StaticRoute<"/components/Icons/prestashopIcon">
    | StaticRoute<"/components/MenuList">
    | StaticRoute<"/components/Menus/CommunityMenu">
    | StaticRoute<"/components/Menus/DomainMenu">
    | StaticRoute<"/components/Menus/HostingMenu">
    | StaticRoute<"/components/Menus/MenuHandler">
    | StaticRoute<"/components/Menus/Partnership">
    | StaticRoute<"/components/Menus/Pricing">
    | StaticRoute<"/components/Svg/BGObject">
    | StaticRoute<"/components/Svg/HeroBg">
    | StaticRoute<"/components/menuActionBanner">
    | StaticRoute<"/dedicated-server-hosting/Components/Features">
    | StaticRoute<"/dedicated-server-hosting/Components/HeroBlock">
    | StaticRoute<"/dedicated-server-hosting/Components/OsApp">
    | StaticRoute<"/dedicated-server-hosting/Components/PricingConfig">
    | StaticRoute<"/dedicated-server-hosting/Components/Section1">
    | StaticRoute<"/dedicated-server-hosting/Components/Section2">
    | StaticRoute<"/dedicated-server-hosting/Components/Section3">
    | StaticRoute<"/dedicated-server-hosting">
    | StaticRoute<"/domain-name-search/Component/CartList">
    | StaticRoute<"/domain-name-search/Component/DomainFeatures">
    | StaticRoute<"/domain-name-search/Component/DomainListRes">
    | StaticRoute<"/domain-name-search/Component/FaqBlock">
    | StaticRoute<"/domain-name-search/Component/LoadingButton">
    | StaticRoute<"/domain-name-search/Component/SearchBar">
    | StaticRoute<"/domain-name-search/Component/Section2">
    | StaticRoute<"/domain-name-search/Component/Section3">
    | StaticRoute<"/domain-name-search/Component/Section4">
    | StaticRoute<"/domain-name-search">
    | StaticRoute<"/domain-name-search/registration">
    | StaticRoute<"/">
    | StaticRoute<"/mt4-hosting">
    | StaticRoute<"/student-web-hosting">
    | StaticRoute<"/web-hosting/Components/FaqBlock">
    | StaticRoute<"/web-hosting/Components/FeaturesBlock">
    | StaticRoute<"/web-hosting/Components/HeroBlock">
    | StaticRoute<"/web-hosting/Components/OverviewBlock">
    | StaticRoute<"/web-hosting/Components/PricingBlock">
    | StaticRoute<"/web-hosting/Components/Section1Block">
    | StaticRoute<"/web-hosting/Components/Section2Block">
    | StaticRoute<"/web-hosting/Components/SectionBlock">
    | StaticRoute<"/web-hosting/Components/WordpressTransfer">
    | StaticRoute<"/web-hosting/Widget/HeroTab">
    | StaticRoute<"/web-hosting">
    | StaticRoute<"/wordpress-ecommerce">
    | StaticRoute<"/wordpress-hosting/Components/FaqBlock">
    | StaticRoute<"/wordpress-hosting/Components/HeroBlock">
    | StaticRoute<"/wordpress-hosting/Components/PricingBlock">
    | StaticRoute<"/wordpress-hosting/Components/Section1Block">
    | StaticRoute<"/wordpress-hosting/Components/Section2Block">
    | StaticRoute<"/wordpress-hosting/Components/SectionOne">
    | StaticRoute<"/wordpress-hosting/Components/SectionThree">
    | StaticRoute<"/wordpress-hosting/Components/SectionTwo">
    | StaticRoute<"/wordpress-hosting">;

  interface StaticRoute<Pathname> {
    pathname: Pathname;
    query?: Query | undefined;
    hash?: string | null | undefined;
  }

  interface DynamicRoute<Pathname, Parameters> {
    pathname: Pathname;
    query: Parameters & Query;
    hash?: string | null | undefined;
  }

  interface Query {
    [key: string]: string | string[] | undefined;
  };

  export type RoutedQuery<P extends Route["pathname"]> = Extract<
    Route,
    { pathname: P }
  >["query"];

  export type Locale = undefined;

  /**
   * A typesafe utility function for generating paths in your application.
   *
   * route({ pathname: "/foos/[foo]", query: { foo: "bar" }}) will produce "/foos/bar".
   */
  export declare function route(r: Route): string;
}

// prettier-ignore
declare module "next/link" {
  import type { Route } from "nextjs-routes";
  import type { LinkProps as NextLinkProps } from "next/dist/client/link";
  import type {
    AnchorHTMLAttributes,
    DetailedReactHTMLElement,
    MouseEventHandler,
    PropsWithChildren,
  } from "react";
  export * from "next/dist/client/link";

  type Query = { query?: { [key: string]: string | string[] | undefined } };
  type StaticRoute = Exclude<Route, { query: any }>["pathname"];

  export interface LinkProps<
    Href extends Route | StaticRoute | Query = Route | StaticRoute | Query
  >
    extends Omit<NextLinkProps, "href" | "locale">,
      AnchorHTMLAttributes<HTMLAnchorElement> {
    href: Href;
    locale?: false;
  }

  type LinkReactElement = DetailedReactHTMLElement<
    {
      onMouseEnter?: MouseEventHandler<Element> | undefined;
      onClick: MouseEventHandler;
      href?: string | undefined;
      ref?: any;
    },
    HTMLElement
  >;

  declare function Link(
    props: PropsWithChildren<LinkProps<Route>>
  ): LinkReactElement;
  declare function Link(
    props: PropsWithChildren<LinkProps<StaticRoute>>
  ): LinkReactElement;
  declare function Link(
    props: PropsWithChildren<LinkProps<Query>>
  ): LinkReactElement;

  export default Link;
}

// prettier-ignore
declare module "next/router" {
  import type { Locale, Route, RoutedQuery } from "nextjs-routes";
  import type { NextRouter as Router } from "next/dist/client/router";
  export * from "next/dist/client/router";
  export { default } from "next/dist/client/router";

  type NextTransitionOptions = NonNullable<Parameters<Router["push"]>[2]>;
  type StaticRoute = Exclude<Route, { query: any }>["pathname"];

  interface TransitionOptions extends Omit<NextTransitionOptions, "locale"> {
    locale?: false;
  }

  export type NextRouter<P extends Route["pathname"] = Route["pathname"]> =
    Extract<Route, { pathname: P }> &
      Omit<
        Router,
        | "push"
        | "replace"
        | "locale"
        | "locales"
        | "defaultLocale"
        | "domainLocales"
      > & {
        defaultLocale?: undefined;
        domainLocales?: undefined;
        locale?: Locale;
        locales?: undefined;
        push(
          url: Route,
          as?: string,
          options?: TransitionOptions
        ): Promise<boolean>;
        push(
          url: StaticRoute,
          as?: string,
          options?: TransitionOptions
        ): Promise<boolean>;
        push(
          url: { query?: { [key: string]: string | string[] | undefined } },
          as?: string,
          options?: TransitionOptions
        ): Promise<boolean>;
        replace(
          url: Route,
          as?: string,
          options?: TransitionOptions
        ): Promise<boolean>;
        replace(
          url: StaticRoute,
          as?: string,
          options?: TransitionOptions
        ): Promise<boolean>;
        replace(
          url: { query?: { [key: string]: string | string[] | undefined } },
          as?: string,
          options?: TransitionOptions
        ): Promise<boolean>;
        route: P;
      };

  export function useRouter<P extends Route["pathname"]>(): NextRouter<P>;
}
